name: Pinterest Automation Final

on:
  schedule:
    - cron: '0 16 * * *' # প্রতিদিন বাংলাদেশ সময় রাত ১০টায় চলবে
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Bot
        env:
          PINTEREST_TOKEN: ${{ secrets.PINTEREST_TOKEN }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: python main.py
